name: charles_click
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  awesome_notifications: ^0.9.3+1
  flutter_native_splash: ^2.4.1
  flutter_inappwebview:
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  flutter_app_lock: ^4.1.1+1
  dio: ^5.7.0
  local_auth: ^2.3.0
  awesome_snackbar_content: ^0.1.4
  prompt_dialog: ^1.0.16
  lottie:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.jpg"
  min_sdk_android: 21

#!  run    flutter pub run flutter_launcher_icons

flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  #todo dart run flutter_native_splash:create
  #? To restore Flutter's default white splash screen, run the following command in the terminal:
  # dart run flutter_native_splash:remove
  image: "assets/mainlogo.png"
  color: "#ffffff"
  #background_image: "assets/background.png"

flutter:
  uses-material-design: true
  assets:
    - assets/mainlogo.png
    - assets/landing-bg.jpg
    - assets/error_lottie.json
