name: charles_click
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.0.0
  awesome_notifications: ^0.9.3+1
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.jpg"
  min_sdk_android: 21

#!  run    flutter pub run flutter_launcher_icons

flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  #todo dart run flutter_native_splash:create
  #? To restore Flutter's default white splash screen, run the following command in the terminal:
  # dart run flutter_native_splash:remove
  image: "assets/mainlogo.png"
  color: "#42a5f5"
  #background_image: "assets/background.png"

flutter:
  uses-material-design: true
